import { useEffect, useMemo, useRef, useState } from "react";
import { useOutletContext } from "react-router-dom";
import QRCode from "qrcode";
import type { DentflowMainLayoutContext } from "../layouts/MainLayout";
import "../styles/machines.css";

type Machine={id:number;name:string;type:string;serialNumber:string;qrToken:string;clinicName:string;targetClinicName:string|null;status:string;isActive:number};
type Reservation={id:number;machineId:number;machineName:string;clinicName:string;scheduledStartAt:string;scheduledEndAt:string;status:string};
type Usage={id:number;machineName:string;clinicName:string;patientNameSnapshot:string;patientBirthDateSnapshot:string;usageDate:string;toothPositions:string[];doctorName:string;status:string;signature:string;signedAt:string|null;unitCost?:number};
type Credit={machineId:number;remainingUses:number;unitCost?:number;updatedAt:string};
const box:React.CSSProperties={background:"#fff",border:"1px solid #d8e4d8",borderRadius:14,padding:18,boxShadow:"0 4px 14px rgba(45,75,55,.035)"};
const field:React.CSSProperties={display:"block",width:"100%",boxSizing:"border-box",minHeight:44,padding:"10px 12px",marginBottom:10,border:"1px solid #cbdacb",borderRadius:9,font:"inherit",background:"#fff"};
const grid:React.CSSProperties={display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(330px,1fr))",gap:16,alignItems:"start"};
const actions:React.CSSProperties={display:"flex",gap:8,flexWrap:"wrap",alignItems:"center"};

function HandwrittenSignature({onChange}:{onChange:(value:string)=>void}){
 const canvasRef=useRef<HTMLCanvasElement>(null),drawing=useRef(false),[hasInk,setHasInk]=useState(false);
 function context(canvas:HTMLCanvasElement){const value=canvas.getContext("2d");if(value){value.lineCap="round";value.lineJoin="round";value.strokeStyle="#173f2f";value.lineWidth=5;}return value;}
 function point(event:React.PointerEvent<HTMLCanvasElement>){const canvas=event.currentTarget,rect=canvas.getBoundingClientRect();return{x:(event.clientX-rect.left)*canvas.width/rect.width,y:(event.clientY-rect.top)*canvas.height/rect.height};}
 function sync(canvas:HTMLCanvasElement){setHasInk(true);onChange(canvas.toDataURL("image/png"));}
 function start(event:React.PointerEvent<HTMLCanvasElement>){event.preventDefault();const canvas=event.currentTarget,p=point(event),value=context(canvas);drawing.current=true;try{canvas.setPointerCapture(event.pointerId);}catch{/* Electron 舊版仍可繼續繪製 */}value?.beginPath();value?.moveTo(p.x,p.y);value?.lineTo(p.x+.5,p.y+.5);value?.stroke();sync(canvas);}
 function move(event:React.PointerEvent<HTMLCanvasElement>){if(!drawing.current)return;event.preventDefault();const p=point(event),value=context(event.currentTarget);value?.lineTo(p.x,p.y);value?.stroke();sync(event.currentTarget);}
 function finish(event:React.PointerEvent<HTMLCanvasElement>){if(!drawing.current)return;event.preventDefault();drawing.current=false;context(event.currentTarget)?.closePath();sync(event.currentTarget);}
 function clear(){const canvas=canvasRef.current;if(canvas)canvas.getContext("2d")?.clearRect(0,0,canvas.width,canvas.height);setHasInk(false);onChange("");}
 return <div><div className="machine-signature-canvas-wrap"><canvas ref={canvasRef} width={900} height={300} onPointerDown={start} onPointerMove={move} onPointerUp={finish} onPointerCancel={finish} onPointerLeave={event=>{if(drawing.current&&event.buttons===0)finish(event);}} aria-label="醫師手寫簽名區"/><span className={hasInk?"has-ink":""}>請在此手寫簽名</span></div><button type="button" className="machine-signature-clear" onClick={clear} disabled={!hasInk}>清除重簽</button></div>;
}

export default function Machines(){
 const {session}=useOutletContext<DentflowMainLayoutContext>(); const admin=session.role==="Admin",assistant=session.role==="Assistant",doctor=session.role==="Doctor",accountant=session.role==="Accountant",canLogistics=admin||assistant,canCost=admin||accountant;
 const [machines,setMachines]=useState<Machine[]>([]),[reservations,setReservations]=useState<Reservation[]>([]),[clinics,setClinics]=useState<DentflowClinicRecord[]>([]),[records,setRecords]=useState<Usage[]>([]),[patients,setPatients]=useState<DentflowPatientRecord[]>([]),[doctors,setDoctors]=useState<DentflowDoctorRecord[]>([]);
 const [credit,setCredit]=useState<Credit|null>(null),[error,setError]=useState(""),[notice,setNotice]=useState(""),[qr,setQr]=useState<Record<number,string>>({}),[creditQty,setCreditQty]=useState(""),[unitCost,setUnitCost]=useState("");
 const [scanToken,setScanToken]=useState(""),[scanReservation,setScanReservation]=useState(""),[machineForm,setMachineForm]=useState({name:"",type:"導航機",serialNumber:""});
 const [editingMachine,setEditingMachine]=useState<Machine|null>(null),[editForm,setEditForm]=useState({name:"",type:"",serialNumber:""}),[isEditingMachine,setIsEditingMachine]=useState(false);
 const [signingRecord,setSigningRecord]=useState<Usage|null>(null),[signature,setSignature]=useState(""),[isSigning,setIsSigning]=useState(false);
 const [reserve,setReserve]=useState({machineId:"",clinicId:String(session.clinicId),scheduledStartAt:"",scheduledEndAt:"",note:"",force:false,overrideReason:""});
 const [usage,setUsage]=useState({machineId:"",patientId:"",doctorId:"",usageDate:new Date().toISOString().slice(0,10),teeth:""});
 async function load(){try{const [m,c,u]=await Promise.all([window.dentflow.machines.list(),window.dentflow.auth.activeClinics(),window.dentflow.machines.usageRecords(session.userId)]);setMachines(m);setClinics(c);setRecords(u);setError("");const nav=m.find((x:Machine)=>x.type.includes("導航"));if(nav){const value=await window.dentflow.machines.usageCredits(nav.id,session.userId);setCredit(value);setUnitCost(String(value.unitCost??""));setUsage(x=>({...x,machineId:x.machineId||String(nav.id)}));}if(canLogistics){const [r,p,d]=await Promise.all([window.dentflow.machines.reservations(),window.dentflow.patients.list(session.clinicId),window.dentflow.doctors.active(session.clinicId)]);setReservations(r);setPatients(p);setDoctors(d);const pairs=await Promise.all(m.map(async(x:Machine)=>[x.id,await QRCode.toDataURL(x.qrToken,{width:180,margin:1})] as const));setQr(Object.fromEntries(pairs));}}catch(e){setError(e instanceof Error?e.message:String(e));}}
 useEffect(()=>{void Promise.resolve().then(load);},[]); const [now]=useState(()=>Date.now()); const reminders=useMemo(()=>reservations.filter(r=>{const start=new Date(r.scheduledStartAt).getTime();return(start-now>0&&start-now<=86400000)||(r.status==="搬運中"&&now-start>1800000);}),[reservations,now]); const selectedPatient=patients.find(p=>p.id===Number(usage.patientId));
 async function run(action:()=>Promise<unknown>,message:string){try{setError("");await action();setNotice(message);await load();}catch(e){setError(e instanceof Error?e.message:String(e));}}
 function openMachineEditor(m:Machine){setEditingMachine(m);setEditForm({name:m.name,type:m.type,serialNumber:m.serialNumber});setError("");}
 async function saveMachine(){if(!editingMachine||!editForm.name.trim()||!editForm.type.trim()){setError("請填寫機台名稱與類型");return;}try{setIsEditingMachine(true);setError("");await window.dentflow.machines.update(editingMachine.id,{name:editForm.name.trim(),type:editForm.type.trim(),serialNumber:editForm.serialNumber.trim()},session.userId);setEditingMachine(null);setNotice("機台資料已更新");await load();}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setIsEditingMachine(false);}}
 function openSignature(r:Usage){setSigningRecord(r);setSignature("");setError("");}
 async function confirmSignature(){if(!signingRecord||!signature.startsWith("data:image/png;base64,")||signature.length<200){setError("請先在簽名欄完成手寫簽名");return;}try{setIsSigning(true);setError("");await window.dentflow.machines.signUsage(signingRecord.id,signature,session.userId);setSigningRecord(null);setSignature("");setNotice("醫師簽名確認完成");await load();}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setIsSigning(false);}}
 return <section className="machines-page"><header className="machines-header"><span>CLINIC EQUIPMENT</span><h1>植牙導航機管理</h1></header>{error&&<div style={{...box,background:"#fff0f0",color:"#a33",marginBottom:14}}>{error}</div>}{notice&&<div style={{...box,background:"#eef8ef",marginBottom:14}}>{notice}</div>}
 {editingMachine&&<div className="machine-signature-backdrop" role="presentation" onMouseDown={e=>{if(e.target===e.currentTarget&&!isEditingMachine)setEditingMachine(null);}}><div className="machine-signature-dialog machine-edit-dialog" role="dialog" aria-modal="true" aria-labelledby="machine-edit-title"><div className="machine-signature-title"><div><span>MACHINE SETTINGS</span><h2 id="machine-edit-title">編輯機台資料</h2></div><button type="button" className="machine-signature-close" disabled={isEditingMachine} onClick={()=>setEditingMachine(null)}>×</button></div><div className="machine-edit-fields"><label>機台名稱<input autoFocus value={editForm.name} onChange={e=>setEditForm({...editForm,name:e.target.value})}/></label><label>機台類型<select value={editForm.type} onChange={e=>setEditForm({...editForm,type:e.target.value})}><option value="導航機">導航機</option><option value="水雷射">水雷射</option><option value="其他大型機台">其他大型機台</option></select></label><label>機台序號<input value={editForm.serialNumber} onChange={e=>setEditForm({...editForm,serialNumber:e.target.value})} placeholder="未設定序號"/></label></div><div className="machine-current-location"><small>目前所在院所</small><strong>{editingMachine.status==="搬運中"?`${editingMachine.clinicName} → ${editingMachine.targetClinicName??"目的院所"}`:editingMachine.clinicName}</strong><span>{editingMachine.status}</span></div><div className="machine-signature-actions"><button type="button" className="machine-signature-cancel" disabled={isEditingMachine} onClick={()=>setEditingMachine(null)}>取消</button><button type="button" disabled={isEditingMachine||!editForm.name.trim()||!editForm.type.trim()} onClick={()=>void saveMachine()}>{isEditingMachine?"儲存中…":"儲存修改"}</button></div></div></div>}
 {signingRecord&&<div className="machine-signature-backdrop" role="presentation" onMouseDown={e=>{if(e.target===e.currentTarget&&!isSigning)setSigningRecord(null);}}><div className="machine-signature-dialog" role="dialog" aria-modal="true" aria-labelledby="machine-signature-title"><div className="machine-signature-title"><div><span>DOCTOR SIGNATURE</span><h2 id="machine-signature-title">醫師手寫簽名確認</h2></div><button type="button" className="machine-signature-close" disabled={isSigning} onClick={()=>setSigningRecord(null)}>×</button></div><div className="machine-signature-summary"><div><small>病患</small><strong>{signingRecord.patientNameSnapshot}</strong></div><div><small>使用日期</small><strong>{signingRecord.usageDate}</strong></div><div><small>牙位</small><strong>{signingRecord.toothPositions.join("、")}</strong></div><div><small>院所</small><strong>{signingRecord.clinicName}</strong></div></div><label className="machine-signature-field">醫師手寫簽名<HandwrittenSignature onChange={setSignature}/></label><p className="machine-signature-note">可使用滑鼠、觸控筆或手指簽名。送出後將連同簽名時間保留於紀錄。</p><div className="machine-signature-actions"><button type="button" className="machine-signature-cancel" disabled={isSigning} onClick={()=>setSigningRecord(null)}>取消</button><button type="button" disabled={isSigning||!signature} onClick={()=>void confirmSignature()}>{isSigning?"簽名中…":"確認簽名"}</button></div></div></div>}
 {credit&&credit.remainingUses<5&&<div style={{...box,background:"#fff3d7",borderColor:"#dfad39",marginBottom:14}}><strong>購買額度提醒：</strong>導航機僅剩 {credit.remainingUses} 次可用，請助理儘速購買額度。</div>}
 <div style={{...grid,marginBottom:16}}><div style={box}><h2 style={{marginTop:0}}>全院所共用額度</h2><div style={{fontSize:42,fontWeight:800}}>{credit?.remainingUses??"—"}<small style={{fontSize:16}}> 次</small></div><p>每位病患每次使用固定扣除 1 次，多顆牙位不重複扣除。</p>{(admin||assistant)&&<div style={actions}><input style={{...field,width:150,margin:0}} type="number" min="1" step="1" placeholder="購買次數" value={creditQty} onChange={e=>setCreditQty(e.target.value)}/><button onClick={()=>void run(()=>window.dentflow.machines.purchaseCredits(Number(credit?.machineId),Number(creditQty),session.userId),"額度已加入")}>加入購買額度</button></div>}{canCost&&<div style={{...actions,marginTop:12}}><input style={{...field,width:150,margin:0}} type="number" min="0" placeholder="每次成本" value={unitCost} onChange={e=>setUnitCost(e.target.value)}/><button onClick={()=>void run(()=>window.dentflow.machines.updateUsageCost(Number(credit?.machineId),Number(unitCost),session.userId),"每次使用成本已更新")}>儲存成本</button></div>}</div>
 {canLogistics&&<div style={box}><h2 style={{marginTop:0}}>登記病患使用</h2><select style={field} value={usage.patientId} onChange={e=>setUsage({...usage,patientId:e.target.value})}><option value="">選擇病患</option>{patients.map(p=><option key={p.id} value={p.id}>{p.chartNumber}｜{p.name}</option>)}</select>{selectedPatient&&<div style={{marginBottom:10}}>生日：{selectedPatient.birthDate||"未填寫"}</div>}<select style={field} value={usage.doctorId} onChange={e=>setUsage({...usage,doctorId:e.target.value})}><option value="">選擇醫師</option>{doctors.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select><input style={field} type="date" value={usage.usageDate} onChange={e=>setUsage({...usage,usageDate:e.target.value})}/><input style={field} placeholder="牙位，例如：11、12、21" value={usage.teeth} onChange={e=>setUsage({...usage,teeth:e.target.value})}/><button onClick={()=>void run(()=>window.dentflow.machines.createUsage({machineId:Number(usage.machineId),clinicId:session.clinicId,patientId:Number(usage.patientId),usageDate:usage.usageDate,toothPositions:usage.teeth.split(/[、,，\s]+/),doctorId:Number(usage.doctorId)},session.userId),"使用紀錄已建立並扣除 1 次額度")}>建立紀錄並扣 1 次</button></div>}</div>
 <div style={{...box,marginBottom:16,overflowX:"auto"}}><h2 style={{marginTop:0}}>{doctor?"我的導航使用紀錄":"全院所導航使用紀錄"}</h2><table style={{width:"100%",borderCollapse:"collapse",minWidth:850}}><thead><tr>{["院所","病患","生日","使用日期","牙位","醫師","狀態",...(canCost?["每次成本"]:[]),"操作"].map(h=><th key={h} style={{textAlign:"left",padding:10,borderBottom:"1px solid #dfe7df"}}>{h}</th>)}</tr></thead><tbody>{records.map(r=><tr key={r.id}><td style={{padding:10}}>{r.clinicName}</td><td>{r.patientNameSnapshot}</td><td>{r.patientBirthDateSnapshot||"—"}</td><td>{r.usageDate}</td><td>{r.toothPositions.join("、")}</td><td>{r.doctorName}</td><td>{r.status}</td>{canCost&&<td>NT$ {Number(r.unitCost??0).toLocaleString()}</td>}<td>{doctor&&r.status==="待醫師簽名"?<button onClick={()=>openSignature(r)}>簽名確認</button>:r.signature?.startsWith("data:image/")?<img className="machine-signature-preview" src={r.signature} alt={`${r.doctorName} 的簽名`}/>:r.signature||"—"}</td></tr>)}{records.length===0&&<tr><td colSpan={canCost?9:8} style={{padding:30,textAlign:"center"}}>目前沒有使用紀錄</td></tr>}</tbody></table></div>
 {canLogistics&&<><div className="machine-location-overview">{machines.map(m=><div key={m.id}><span>{m.name}</span><strong>{m.status==="搬運中"?"搬運中":`目前在 ${m.clinicName}`}</strong>{m.status==="搬運中"&&<small>{m.clinicName} → {m.targetClinicName??"待確認"}</small>}</div>)}</div><div style={grid}><div style={box}><h2 style={{marginTop:0}}>機台位置與 QR</h2>{machines.map(m=><div key={m.id} style={{display:"flex",gap:14,padding:"12px 0",borderTop:"1px solid #edf1ed"}}><img src={qr[m.id]} width={90} height={90}/><div><strong>{m.name}</strong><div>{m.type}｜{m.serialNumber||"無序號"}</div><div className="machine-location-label">目前所在：{m.clinicName}{m.targetClinicName?` → ${m.targetClinicName}`:""}</div><div>狀態：{m.status}</div>{admin&&<div style={actions}><button onClick={()=>openMachineEditor(m)}>編輯</button><button onClick={()=>void run(()=>window.dentflow.machines.setActive(m.id,!m.isActive,session.userId),"機台狀態已更新")}>{m.isActive?"停用":"啟用"}</button></div>}</div></div>)}</div>
 <div style={box}><h2 style={{marginTop:0}}>預約機台</h2><select style={field} value={reserve.machineId} onChange={e=>setReserve({...reserve,machineId:e.target.value})}><option value="">選擇機台</option>{machines.filter(m=>m.isActive).map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select><select style={field} value={reserve.clinicId} onChange={e=>setReserve({...reserve,clinicId:e.target.value})}>{clinics.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><input style={field} type="datetime-local" value={reserve.scheduledStartAt} onChange={e=>setReserve({...reserve,scheduledStartAt:e.target.value})}/><input style={field} type="datetime-local" value={reserve.scheduledEndAt} onChange={e=>setReserve({...reserve,scheduledEndAt:e.target.value})}/>{admin&&<><label><input type="checkbox" checked={reserve.force} onChange={e=>setReserve({...reserve,force:e.target.checked})}/> 管理者強制覆寫衝突</label>{reserve.force&&<input style={{...field,marginTop:10}} placeholder="覆寫原因（必填）" value={reserve.overrideReason} onChange={e=>setReserve({...reserve,overrideReason:e.target.value})}/>}</>}<button onClick={()=>void run(()=>window.dentflow.machines.reserve({...reserve,machineId:Number(reserve.machineId),clinicId:Number(reserve.clinicId),moverUserId:session.userId},session.userId),"預約已建立")}>建立預約</button></div>
 <div style={box}><h2 style={{marginTop:0}}>QR 交接掃描</h2><input style={field} placeholder="掃描機台 QR Code" value={scanToken} onChange={e=>setScanToken(e.target.value)}/><select style={field} value={scanReservation} onChange={e=>setScanReservation(e.target.value)}><option value="">選擇預約</option>{reservations.map(r=><option key={r.id} value={r.id}>{r.machineName} → {r.clinicName}</option>)}</select><div style={actions}>{(["搬出","到院"] as const).map(a=><button key={a} onClick={()=>void run(()=>window.dentflow.machines.scan(scanToken,Number(scanReservation),session.clinicId,a,session.userId),`${a}確認完成`)}>{a}確認</button>)}</div></div>
 {admin&&<div style={box}><h2 style={{marginTop:0}}>新增機台</h2><input style={field} placeholder="機台名稱" value={machineForm.name} onChange={e=>setMachineForm({...machineForm,name:e.target.value})}/><select style={field} value={machineForm.type} onChange={e=>setMachineForm({...machineForm,type:e.target.value})}><option>導航機</option><option>水雷射</option><option>其他大型機台</option></select><input style={field} placeholder="序號" value={machineForm.serialNumber} onChange={e=>setMachineForm({...machineForm,serialNumber:e.target.value})}/><button onClick={()=>void run(()=>window.dentflow.machines.create({...machineForm,clinicId:session.clinicId},session.userId),"機台已新增")}>新增機台</button></div>}</div><div style={{...box,marginTop:16}}><div className="machine-schedule-heading"><h2 style={{margin:0}}>已預約時段</h2><span>共 {reservations.length} 筆</span></div>{reservations.length===0?<div className="machine-schedule-empty">目前沒有機台預約</div>:<div className="machine-schedule-list">{reservations.map(r=><div key={r.id}><strong>{r.machineName}</strong><span>{r.clinicName}</span><time>{new Date(r.scheduledStartAt).toLocaleString()} ～ {new Date(r.scheduledEndAt).toLocaleString()}</time><em>{r.status}</em></div>)}</div>}</div>{reminders.length>0&&<div style={{...box,background:"#fff8e7",marginTop:16}}>{reminders.map(r=><div key={r.id}>{r.status==="搬運中"?"到院確認已逾時 30 分鐘":"預約將於 1 天內開始"}：{r.machineName} → {r.clinicName}</div>)}</div>}</>}
 </section>;
}
