import { useEffect, useMemo, useState } from "react";
import { useOutletContext } from "react-router-dom";
import QRCode from "qrcode";
import type { DentflowMainLayoutContext } from "../layouts/MainLayout";

type Machine={id:number;name:string;type:string;serialNumber:string;qrToken:string;clinicName:string;targetClinicName:string|null;status:string;isActive:number};
type Reservation={id:number;machineName:string;clinicName:string;scheduledStartAt:string;status:string};
type Usage={id:number;machineName:string;clinicName:string;patientNameSnapshot:string;patientBirthDateSnapshot:string;usageDate:string;toothPositions:string[];doctorName:string;status:string;signature:string;signedAt:string|null;unitCost?:number};
type Credit={machineId:number;remainingUses:number;unitCost?:number;updatedAt:string};
const box:React.CSSProperties={background:"#fff",border:"1px solid #dfe7df",borderRadius:16,padding:20,boxShadow:"0 5px 18px rgba(45,75,55,.05)"};
const field:React.CSSProperties={display:"block",width:"100%",boxSizing:"border-box",padding:"10px 12px",marginBottom:10,border:"1px solid #ced9cf",borderRadius:9,font:"inherit",background:"#fff"};
const grid:React.CSSProperties={display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(330px,1fr))",gap:16,alignItems:"start"};
const actions:React.CSSProperties={display:"flex",gap:8,flexWrap:"wrap",alignItems:"center"};

export default function Machines(){
 const {session}=useOutletContext<DentflowMainLayoutContext>(); const admin=session.role==="Admin",assistant=session.role==="Assistant",doctor=session.role==="Doctor",accountant=session.role==="Accountant",canLogistics=admin||assistant,canCost=admin||accountant;
 const [machines,setMachines]=useState<Machine[]>([]),[reservations,setReservations]=useState<Reservation[]>([]),[clinics,setClinics]=useState<DentflowClinicRecord[]>([]),[records,setRecords]=useState<Usage[]>([]),[patients,setPatients]=useState<DentflowPatientRecord[]>([]),[doctors,setDoctors]=useState<DentflowDoctorRecord[]>([]);
 const [credit,setCredit]=useState<Credit|null>(null),[error,setError]=useState(""),[notice,setNotice]=useState(""),[qr,setQr]=useState<Record<number,string>>({}),[creditQty,setCreditQty]=useState(""),[unitCost,setUnitCost]=useState("");
 const [scanToken,setScanToken]=useState(""),[scanReservation,setScanReservation]=useState(""),[machineForm,setMachineForm]=useState({name:"",type:"導航機",serialNumber:""});
 const [reserve,setReserve]=useState({machineId:"",clinicId:String(session.clinicId),scheduledStartAt:"",scheduledEndAt:"",note:"",force:false,overrideReason:""});
 const [usage,setUsage]=useState({machineId:"",patientId:"",doctorId:"",usageDate:new Date().toISOString().slice(0,10),teeth:""});
 async function load(){try{const [m,c,u]=await Promise.all([window.dentflow.machines.list(),window.dentflow.auth.activeClinics(),window.dentflow.machines.usageRecords(session.userId)]);setMachines(m);setClinics(c);setRecords(u);setError("");const nav=m.find((x:Machine)=>x.type.includes("導航"));if(nav){const value=await window.dentflow.machines.usageCredits(nav.id,session.userId);setCredit(value);setUnitCost(String(value.unitCost??""));setUsage(x=>({...x,machineId:x.machineId||String(nav.id)}));}if(canLogistics){const [r,p,d]=await Promise.all([window.dentflow.machines.reservations(),window.dentflow.patients.list(session.clinicId),window.dentflow.doctors.active(session.clinicId)]);setReservations(r);setPatients(p);setDoctors(d);const pairs=await Promise.all(m.map(async(x:Machine)=>[x.id,await QRCode.toDataURL(x.qrToken,{width:180,margin:1})] as const));setQr(Object.fromEntries(pairs));}}catch(e){setError(e instanceof Error?e.message:String(e));}}
 useEffect(()=>{void Promise.resolve().then(load);},[]); const [now]=useState(()=>Date.now()); const reminders=useMemo(()=>reservations.filter(r=>{const start=new Date(r.scheduledStartAt).getTime();return(start-now>0&&start-now<=86400000)||(r.status==="搬運中"&&now-start>1800000);}),[reservations,now]); const selectedPatient=patients.find(p=>p.id===Number(usage.patientId));
 async function run(action:()=>Promise<unknown>,message:string){try{setError("");await action();setNotice(message);await load();}catch(e){setError(e instanceof Error?e.message:String(e));}}
 async function editMachine(m:Machine){const name=window.prompt("機台名稱",m.name)?.trim();if(!name)return;const type=window.prompt("機台類型",m.type)?.trim();if(!type)return;const serialNumber=window.prompt("機台序號",m.serialNumber)?.trim()??m.serialNumber;await run(()=>window.dentflow.machines.update(m.id,{name,type,serialNumber},session.userId),"機台資料已更新");}
 async function sign(r:Usage){const signature=window.prompt("請輸入醫師簽名",session.name)?.trim();if(signature)await run(()=>window.dentflow.machines.signUsage(r.id,signature,session.userId),"簽名完成");}
 return <section style={{padding:28,color:"#234634"}}><h1>植牙導航機管理</h1>{error&&<div style={{...box,background:"#fff0f0",color:"#a33",marginBottom:14}}>{error}</div>}{notice&&<div style={{...box,background:"#eef8ef",marginBottom:14}}>{notice}</div>}
 {credit&&credit.remainingUses<5&&<div style={{...box,background:"#fff3d7",borderColor:"#dfad39",marginBottom:14}}><strong>購買額度提醒：</strong>導航機僅剩 {credit.remainingUses} 次可用，請助理儘速購買額度。</div>}
 <div style={{...grid,marginBottom:16}}><div style={box}><h2 style={{marginTop:0}}>全院所共用額度</h2><div style={{fontSize:42,fontWeight:800}}>{credit?.remainingUses??"—"}<small style={{fontSize:16}}> 次</small></div><p>每位病患每次使用固定扣除 1 次，多顆牙位不重複扣除。</p>{(admin||assistant)&&<div style={actions}><input style={{...field,width:150,margin:0}} type="number" min="1" step="1" placeholder="購買次數" value={creditQty} onChange={e=>setCreditQty(e.target.value)}/><button onClick={()=>void run(()=>window.dentflow.machines.purchaseCredits(Number(credit?.machineId),Number(creditQty),session.userId),"額度已加入")}>加入購買額度</button></div>}{canCost&&<div style={{...actions,marginTop:12}}><input style={{...field,width:150,margin:0}} type="number" min="0" placeholder="每次成本" value={unitCost} onChange={e=>setUnitCost(e.target.value)}/><button onClick={()=>void run(()=>window.dentflow.machines.updateUsageCost(Number(credit?.machineId),Number(unitCost),session.userId),"每次使用成本已更新")}>儲存成本</button></div>}</div>
 {canLogistics&&<div style={box}><h2 style={{marginTop:0}}>登記病患使用</h2><select style={field} value={usage.patientId} onChange={e=>setUsage({...usage,patientId:e.target.value})}><option value="">選擇病患</option>{patients.map(p=><option key={p.id} value={p.id}>{p.chartNumber}｜{p.name}</option>)}</select>{selectedPatient&&<div style={{marginBottom:10}}>生日：{selectedPatient.birthDate||"未填寫"}</div>}<select style={field} value={usage.doctorId} onChange={e=>setUsage({...usage,doctorId:e.target.value})}><option value="">選擇醫師</option>{doctors.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select><input style={field} type="date" value={usage.usageDate} onChange={e=>setUsage({...usage,usageDate:e.target.value})}/><input style={field} placeholder="牙位，例如：11、12、21" value={usage.teeth} onChange={e=>setUsage({...usage,teeth:e.target.value})}/><button onClick={()=>void run(()=>window.dentflow.machines.createUsage({machineId:Number(usage.machineId),clinicId:session.clinicId,patientId:Number(usage.patientId),usageDate:usage.usageDate,toothPositions:usage.teeth.split(/[、,，\s]+/),doctorId:Number(usage.doctorId)},session.userId),"使用紀錄已建立並扣除 1 次額度")}>建立紀錄並扣 1 次</button></div>}</div>
 <div style={{...box,marginBottom:16,overflowX:"auto"}}><h2 style={{marginTop:0}}>{doctor?"我的導航使用紀錄":"全院所導航使用紀錄"}</h2><table style={{width:"100%",borderCollapse:"collapse",minWidth:850}}><thead><tr>{["院所","病患","生日","使用日期","牙位","醫師","狀態",...(canCost?["每次成本"]:[]),"操作"].map(h=><th key={h} style={{textAlign:"left",padding:10,borderBottom:"1px solid #dfe7df"}}>{h}</th>)}</tr></thead><tbody>{records.map(r=><tr key={r.id}><td style={{padding:10}}>{r.clinicName}</td><td>{r.patientNameSnapshot}</td><td>{r.patientBirthDateSnapshot||"—"}</td><td>{r.usageDate}</td><td>{r.toothPositions.join("、")}</td><td>{r.doctorName}</td><td>{r.status}</td>{canCost&&<td>NT$ {Number(r.unitCost??0).toLocaleString()}</td>}<td>{doctor&&r.status==="待醫師簽名"?<button onClick={()=>void sign(r)}>簽名確認</button>:r.signature||"—"}</td></tr>)}{records.length===0&&<tr><td colSpan={canCost?9:8} style={{padding:30,textAlign:"center"}}>目前沒有使用紀錄</td></tr>}</tbody></table></div>
 {canLogistics&&<><div style={grid}><div style={box}><h2 style={{marginTop:0}}>機台位置與 QR</h2>{machines.map(m=><div key={m.id} style={{display:"flex",gap:14,padding:"12px 0",borderTop:"1px solid #edf1ed"}}><img src={qr[m.id]} width={90} height={90}/><div><strong>{m.name}</strong><div>{m.type}｜{m.serialNumber||"無序號"}</div><div>{m.status}｜{m.clinicName}{m.targetClinicName?` → ${m.targetClinicName}`:""}</div>{admin&&<div style={actions}><button onClick={()=>void editMachine(m)}>編輯</button><button onClick={()=>void run(()=>window.dentflow.machines.setActive(m.id,!m.isActive,session.userId),"機台狀態已更新")}>{m.isActive?"停用":"啟用"}</button></div>}</div></div>)}</div>
 <div style={box}><h2 style={{marginTop:0}}>預約機台</h2><select style={field} value={reserve.machineId} onChange={e=>setReserve({...reserve,machineId:e.target.value})}><option value="">選擇機台</option>{machines.filter(m=>m.isActive).map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select><select style={field} value={reserve.clinicId} onChange={e=>setReserve({...reserve,clinicId:e.target.value})}>{clinics.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><input style={field} type="datetime-local" value={reserve.scheduledStartAt} onChange={e=>setReserve({...reserve,scheduledStartAt:e.target.value})}/><input style={field} type="datetime-local" value={reserve.scheduledEndAt} onChange={e=>setReserve({...reserve,scheduledEndAt:e.target.value})}/>{admin&&<><label><input type="checkbox" checked={reserve.force} onChange={e=>setReserve({...reserve,force:e.target.checked})}/> 管理者強制覆寫衝突</label>{reserve.force&&<input style={{...field,marginTop:10}} placeholder="覆寫原因（必填）" value={reserve.overrideReason} onChange={e=>setReserve({...reserve,overrideReason:e.target.value})}/>}</>}<button onClick={()=>void run(()=>window.dentflow.machines.reserve({...reserve,machineId:Number(reserve.machineId),clinicId:Number(reserve.clinicId),moverUserId:session.userId},session.userId),"預約已建立")}>建立預約</button></div>
 <div style={box}><h2 style={{marginTop:0}}>QR 交接掃描</h2><input style={field} placeholder="掃描機台 QR Code" value={scanToken} onChange={e=>setScanToken(e.target.value)}/><select style={field} value={scanReservation} onChange={e=>setScanReservation(e.target.value)}><option value="">選擇預約</option>{reservations.map(r=><option key={r.id} value={r.id}>{r.machineName} → {r.clinicName}</option>)}</select><div style={actions}>{(["搬出","到院"] as const).map(a=><button key={a} onClick={()=>void run(()=>window.dentflow.machines.scan(scanToken,Number(scanReservation),session.clinicId,a,session.userId),`${a}確認完成`)}>{a}確認</button>)}</div></div>
 {admin&&<div style={box}><h2 style={{marginTop:0}}>新增機台</h2><input style={field} placeholder="機台名稱" value={machineForm.name} onChange={e=>setMachineForm({...machineForm,name:e.target.value})}/><select style={field} value={machineForm.type} onChange={e=>setMachineForm({...machineForm,type:e.target.value})}><option>導航機</option><option>水雷射</option><option>其他大型機台</option></select><input style={field} placeholder="序號" value={machineForm.serialNumber} onChange={e=>setMachineForm({...machineForm,serialNumber:e.target.value})}/><button onClick={()=>void run(()=>window.dentflow.machines.create({...machineForm,clinicId:session.clinicId},session.userId),"機台已新增")}>新增機台</button></div>}</div>{reminders.length>0&&<div style={{...box,background:"#fff8e7",marginTop:16}}>{reminders.map(r=><div key={r.id}>{r.status==="搬運中"?"到院確認已逾時 30 分鐘":"預約將於 1 天內開始"}：{r.machineName} → {r.clinicName}</div>)}</div>}</>}
 </section>;
}
