CREATE TABLE clinics (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  legacy_id bigint UNIQUE,
  name text NOT NULL,
  active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE users (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  legacy_id bigint UNIQUE,
  account text NOT NULL,
  password_hash text NOT NULL,
  display_name text NOT NULL,
  role text NOT NULL CHECK (role IN ('admin', 'doctor', 'assistant')),
  active boolean NOT NULL DEFAULT true,
  token_version integer NOT NULL DEFAULT 1,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX users_account_lower_unique ON users (lower(account));

CREATE TABLE user_clinics (
  user_id bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  clinic_id bigint NOT NULL REFERENCES clinics(id) ON DELETE CASCADE,
  is_primary boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, clinic_id)
);

CREATE UNIQUE INDEX user_clinics_one_primary_per_user
  ON user_clinics (user_id)
  WHERE is_primary;

CREATE TABLE sessions (
  id uuid PRIMARY KEY,
  user_id bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  token_hash bytea NOT NULL UNIQUE,
  token_version integer NOT NULL,
  device_id text NOT NULL,
  selected_clinic_id bigint REFERENCES clinics(id),
  expires_at timestamptz NOT NULL,
  last_seen_at timestamptz NOT NULL DEFAULT now(),
  revoked_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX sessions_user_active_idx
  ON sessions (user_id, expires_at)
  WHERE revoked_at IS NULL;

CREATE TABLE audit_events (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  occurred_at timestamptz NOT NULL DEFAULT now(),
  actor_user_id bigint REFERENCES users(id),
  clinic_id bigint REFERENCES clinics(id),
  session_id uuid REFERENCES sessions(id),
  device_id text,
  request_id text NOT NULL,
  event_type text NOT NULL,
  entity_type text,
  entity_id text,
  ip inet,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb
);

CREATE INDEX audit_events_clinic_time_idx ON audit_events (clinic_id, occurred_at DESC);
CREATE INDEX audit_events_actor_time_idx ON audit_events (actor_user_id, occurred_at DESC);

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

CREATE TRIGGER clinics_set_updated_at
BEFORE UPDATE ON clinics
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER users_set_updated_at
BEFORE UPDATE ON users
FOR EACH ROW EXECUTE FUNCTION set_updated_at();
