CREATE TABLE patients (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  legacy_id bigint UNIQUE,
  clinic_id bigint NOT NULL REFERENCES clinics(id),
  chart_number text NOT NULL,
  name text NOT NULL,
  birth_date date,
  doctor_user_id bigint REFERENCES users(id),
  doctor_name text NOT NULL DEFAULT '',
  note text NOT NULL DEFAULT '',
  active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX patients_chart_number_unique
  ON patients (chart_number);

CREATE INDEX patients_clinic_name_idx
  ON patients (clinic_id, name, id)
  WHERE active = true;

CREATE INDEX patients_doctor_idx
  ON patients (doctor_user_id, clinic_id)
  WHERE active = true;

CREATE TRIGGER patients_set_updated_at
BEFORE UPDATE ON patients
FOR EACH ROW EXECUTE FUNCTION set_updated_at();
