-- A case is staged for migration, not enabled for stock/workflow writes.
ALTER TABLE patients ADD CONSTRAINT patients_id_clinic_unique UNIQUE (id, clinic_id);

CREATE TABLE implant_cases (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  clinic_id bigint NOT NULL REFERENCES clinics(id),
  patient_id bigint NOT NULL,
  doctor_user_id bigint REFERENCES users(id),
  implant_date text NOT NULL DEFAULT '',
  note text NOT NULL DEFAULT '',
  status text NOT NULL CHECK (status IN (
    '待醫師叫貨','醫師已叫貨','已取出待手術','待術後紀錄',
    '待歸回品項','已完成','已結案','已取消'
  )),
  migration_state text NOT NULL DEFAULT 'legacy_staged' CHECK (migration_state = 'legacy_staged'),
  created_at timestamptz NOT NULL DEFAULT now(),
  FOREIGN KEY (patient_id, clinic_id) REFERENCES patients(id, clinic_id),
  UNIQUE (id, clinic_id)
);

CREATE INDEX implant_cases_clinic_patient_idx ON implant_cases (clinic_id, patient_id, id);
CREATE INDEX implant_cases_doctor_idx ON implant_cases (doctor_user_id, clinic_id);

CREATE TABLE legacy_implant_mappings (
  source_id text NOT NULL,
  legacy_implant_id bigint NOT NULL CHECK (legacy_implant_id > 0),
  implant_case_id bigint NOT NULL UNIQUE,
  clinic_id bigint NOT NULL REFERENCES clinics(id),
  snapshot_hash text NOT NULL CHECK (snapshot_hash ~ '^[0-9a-f]{64}$'),
  imported_by_user_id bigint NOT NULL REFERENCES users(id),
  imported_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (source_id, legacy_implant_id),
  FOREIGN KEY (implant_case_id, clinic_id) REFERENCES implant_cases(id, clinic_id)
);

-- All IDs inside snapshot are legacy IDs scoped to mappings.source_id.
-- Images/signatures remain in SQLite; only their manifests are stored here.
CREATE TABLE legacy_implant_snapshots (
  implant_case_id bigint PRIMARY KEY REFERENCES implant_cases(id),
  snapshot jsonb NOT NULL,
  assets jsonb NOT NULL DEFAULT '[]'::jsonb CHECK (jsonb_typeof(assets) = 'array'),
  pending_asset_count integer NOT NULL CHECK (pending_asset_count >= 0)
);
