CREATE TABLE inventory_batches (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  clinic_id bigint NOT NULL REFERENCES clinics(id),
  name text NOT NULL,
  category text NOT NULL,
  brand text NOT NULL DEFAULT '',
  model text NOT NULL DEFAULT '',
  specification text NOT NULL DEFAULT '',
  ref_number text NOT NULL DEFAULT '',
  lot_number text NOT NULL DEFAULT '',
  expiry_date text NOT NULL DEFAULT '',
  migration_state text NOT NULL DEFAULT 'legacy_staged' CHECK (migration_state='legacy_staged'),
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (id, clinic_id)
);

-- No operational quantity here: quantities from independent computers must
-- be reconciled before activation, never automatically added together.
CREATE TABLE legacy_inventory_mappings (
  source_id text NOT NULL,
  legacy_inventory_id bigint NOT NULL CHECK (legacy_inventory_id>0),
  clinic_id bigint NOT NULL REFERENCES clinics(id),
  inventory_batch_id bigint NOT NULL,
  snapshot_hash text NOT NULL CHECK (snapshot_hash ~ '^[0-9a-f]{64}$'),
  snapshot jsonb NOT NULL,
  imported_by_user_id bigint NOT NULL REFERENCES users(id),
  imported_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (source_id, legacy_inventory_id),
  UNIQUE (source_id, legacy_inventory_id, clinic_id, inventory_batch_id),
  FOREIGN KEY (inventory_batch_id, clinic_id) REFERENCES inventory_batches(id, clinic_id)
);

CREATE INDEX inventory_batches_clinic_idx ON inventory_batches (clinic_id, id);

CREATE TABLE legacy_user_mappings (
  source_id text NOT NULL,
  legacy_user_id bigint NOT NULL CHECK (legacy_user_id>0),
  clinic_id bigint NOT NULL REFERENCES clinics(id),
  user_id bigint NOT NULL REFERENCES users(id),
  source_account text NOT NULL,
  source_role text NOT NULL,
  imported_by_user_id bigint NOT NULL REFERENCES users(id),
  imported_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (source_id, legacy_user_id, clinic_id),
  UNIQUE (source_id, legacy_user_id, clinic_id, user_id)
);

ALTER TABLE legacy_implant_mappings ADD CONSTRAINT legacy_implant_source_clinic_unique
  UNIQUE (implant_case_id, source_id, clinic_id);

CREATE TABLE legacy_implant_inventory_links (
  implant_case_id bigint NOT NULL,
  source_id text NOT NULL,
  clinic_id bigint NOT NULL,
  legacy_inventory_id bigint NOT NULL,
  inventory_batch_id bigint NOT NULL,
  PRIMARY KEY (implant_case_id, legacy_inventory_id),
  FOREIGN KEY (implant_case_id, source_id, clinic_id)
    REFERENCES legacy_implant_mappings(implant_case_id, source_id, clinic_id),
  FOREIGN KEY (source_id, legacy_inventory_id, clinic_id, inventory_batch_id)
    REFERENCES legacy_inventory_mappings(source_id, legacy_inventory_id, clinic_id, inventory_batch_id)
);

CREATE TABLE legacy_implant_user_links (
  implant_case_id bigint NOT NULL,
  source_id text NOT NULL,
  clinic_id bigint NOT NULL,
  legacy_user_id bigint NOT NULL,
  user_id bigint NOT NULL,
  PRIMARY KEY (implant_case_id, legacy_user_id),
  FOREIGN KEY (implant_case_id, source_id, clinic_id)
    REFERENCES legacy_implant_mappings(implant_case_id, source_id, clinic_id),
  FOREIGN KEY (source_id, legacy_user_id, clinic_id, user_id)
    REFERENCES legacy_user_mappings(source_id, legacy_user_id, clinic_id, user_id)
);

ALTER TABLE legacy_implant_snapshots
  ADD COLUMN pending_inventory_refs integer CHECK (pending_inventory_refs>=0),
  ADD COLUMN pending_user_refs integer CHECK (pending_user_refs>=0);
