ALTER TABLE implant_cases DROP CONSTRAINT implant_cases_migration_state_check;
ALTER TABLE implant_cases ADD CONSTRAINT implant_cases_migration_state_check
  CHECK (migration_state IN ('legacy_staged','central_draft'));
ALTER TABLE implant_cases ADD COLUMN version integer NOT NULL DEFAULT 1 CHECK (version>0);
ALTER TABLE implant_cases ADD COLUMN updated_at timestamptz NOT NULL DEFAULT now();
ALTER TABLE implant_cases ADD COLUMN created_by_user_id bigint REFERENCES users(id);
ALTER TABLE implant_cases ADD COLUMN create_request_id uuid;
ALTER TABLE implant_cases ADD COLUMN create_request_hash text;
ALTER TABLE implant_cases ADD COLUMN cancellation_reason text NOT NULL DEFAULT '';
ALTER TABLE implant_cases ADD CONSTRAINT implant_draft_status_check CHECK (
  migration_state <> 'central_draft' OR
  (status IN ('待醫師叫貨','已取消') AND created_by_user_id IS NOT NULL
   AND create_request_id IS NOT NULL AND create_request_hash IS NOT NULL AND create_request_hash ~ '^[0-9a-f]{64}$')
);
CREATE UNIQUE INDEX implant_cases_create_request_unique ON implant_cases(created_by_user_id,create_request_id);
CREATE TRIGGER implant_cases_set_updated_at BEFORE UPDATE ON implant_cases
FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE FUNCTION increment_implant_version() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  NEW.version := OLD.version + 1;
  RETURN NEW;
END;
$$;
CREATE TRIGGER implant_cases_increment_version BEFORE UPDATE ON implant_cases
FOR EACH ROW EXECUTE FUNCTION increment_implant_version();

CREATE TABLE implant_draft_teeth (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  implant_case_id bigint NOT NULL REFERENCES implant_cases(id),
  tooth_position text NOT NULL CHECK (tooth_position ~ '^([1-4][1-8]|[5-8][1-5])$'),
  UNIQUE (implant_case_id,tooth_position),
  UNIQUE (id,implant_case_id)
);
CREATE TABLE implant_draft_plan_items (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  implant_case_id bigint NOT NULL REFERENCES implant_cases(id),
  tooth_id bigint NOT NULL,
  name text NOT NULL CHECK (length(name)>0),
  category text NOT NULL CHECK (category IN ('植體','植體套件','器械')),
  brand text NOT NULL DEFAULT '',
  model text NOT NULL DEFAULT '',
  specification text NOT NULL DEFAULT '',
  planned_quantity integer NOT NULL CHECK (planned_quantity BETWEEN 1 AND 1000),
  FOREIGN KEY (tooth_id,implant_case_id) REFERENCES implant_draft_teeth(id,implant_case_id)
);
CREATE INDEX implant_draft_plan_case_idx ON implant_draft_plan_items(implant_case_id,tooth_id,id);
