export type DispositionOperation="surgery_complete"|"usage"|"return"|"cancel_picked";
export type UsageEntry={reservationId:string;usedQuantity:number};export type ReturnEntry={reservationId:string;quantity:number;returnCondition:"sealed"|"reusable"};
export type DispositionIntent={caseId:number;clinicId:number;expectedVersion:number;requestId:string;operation:DispositionOperation;usages?:UsageEntry[];confirmations?:ReturnEntry[];reason?:string};
export type DispositionResult={id:number;status:string;version:number;entryCount:number;outstandingQuantity:number|null;unchanged:boolean};
const pos=(v:unknown,n:string,zero=false)=>{if(typeof v!=="number"||!Number.isSafeInteger(v)||v<(zero?0:1)||v>1000)throw Error(n+"格式錯誤");return v};
const uuid=(v:unknown)=>{if(typeof v!=="string"||!/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(v))throw Error("識別碼格式錯誤");return v.toLowerCase()};
export function dispositionIntent(v:DispositionIntent){const base={caseId:pos(v.caseId,"個案"),clinicId:pos(v.clinicId,"院所"),expectedVersion:pos(v.expectedVersion,"版本"),requestId:uuid(v.requestId),operation:v.operation};if(!["surgery_complete","usage","return","cancel_picked"].includes(v.operation))throw Error("術後操作格式錯誤");
 if(v.operation==="surgery_complete")return base as DispositionIntent;const entries=v.operation==="usage"?v.usages:v.confirmations;if(!Array.isArray(entries)||!entries.length||entries.length>500)throw Error("須逐項提供術後紀錄");const seen=new Set<string>();
 if(v.operation==="usage")return{...base,usages:(entries as UsageEntry[]).map(e=>{const id=uuid(e.reservationId);if(seen.has(id))throw Error("品項重複");seen.add(id);return{reservationId:id,usedQuantity:pos(e.usedQuantity,"實際使用量",true)}}).sort((a,b)=>a.reservationId.localeCompare(b.reservationId))};
 const reason=typeof v.reason==="string"?v.reason.trim():"";if(!reason||new TextEncoder().encode(reason).length>2000)throw Error("請填寫歸回原因");return{...base,reason,confirmations:(entries as ReturnEntry[]).map(e=>{const id=uuid(e.reservationId);if(seen.has(id)||!["sealed","reusable"].includes(e.returnCondition))throw Error("歸回品項格式錯誤");seen.add(id);return{reservationId:id,quantity:pos(e.quantity,"歸回數量"),returnCondition:e.returnCondition}}).sort((a,b)=>a.reservationId.localeCompare(b.reservationId))};}